### ISSUE TITLE
Could not complete the command because the selected area is empty

### ISSUE THREAD

**Issue by FlorisWarmenhoven** [ndepaola/mtg-autoproxy#4]
Hi bud,

Firstly, I really appreciate the effort you've put in and continue to put in. I recently started to get into Magic and learned about proxies - that got me really excited.

I'm trying to get you script to work, unfortunately I'm stuck on these errors:
![Screenshot 2019-11-15 at 11 52 09](https://user-images.githubusercontent.com/15650071/68938396-98529e80-079e-11ea-9dd9-da81740f60e3.png)
![Screenshot 2019-11-15 at 11 52 18](https://user-images.githubusercontent.com/15650071/68938398-9b4d8f00-079e-11ea-92c7-2d09f2a7014e.png)

These errors happen after I run "proxyAll.jsx". I've had to make adjustments to the scripts. Mostly file references that I had to hardcode. I cloned your repo a few days ago.

What sort of information do you need to help me to debug this?

I am on MacOS Catalina, using Photoshop CC 2018.

**Comment by ndepaola** [comment]
Hi, 

I downloaded PS on my Mac to test this - seems like the issue is that the first file it finds in the folder when doing `proxyAll` is the `.DS_Store` file that's stored invisibly in every folder in macOS. I found a simple fix that I'll push out in a bit!

Is your script running the python script to get the card's info from Scryfall properly within CC 2018? I'm having some issues with that in CC 2020 so I was wondering if you've tweaked that line as well.

Cheers and sorry for the bug!

**Comment by FlorisWarmenhoven** [comment]
Interesting - didn't even think about the .DS_Store folder. I've removed both that folder and the .git folder, just in-case.

I now receive this error:
<img width="1292" alt="Screenshot 2019-11-16 at 10 13 08" src="https://user-images.githubusercontent.com/15650071/68990968-ce088d80-0859-11ea-93c7-3699b601727b.png">

The changes I made to the Python file is by hardcoding all the file references (so instead of storing it in the File variable, I just hard coded `~/Desktop/auto-proxy/scripts` or whichever reference is needed.

Really hope we can debug this together so that this repo can be used on Mac!

**Comment by ndepaola** [comment]
Hmm, I'm not sure I've encountered that error before. Today I spent some time working on fixing filepaths for this, so now I have the same code running properly between both my Windows desktop and Mac. I recommend downloading the most recent version and seeing if that works any better :)

I've seen the issue with weird characters before - that happens when you try to run the script with Python 2.7 instead of Python 3, I believe. Since macOS comes pre-installed with 2.7, you need to specify `python3` when running commands with it. The most recent version addresses this so you shouldn't need to modify this I think.

One issue I haven't been able to fix for my Mac system is the Python script works properly from the command line, but fails to save `card.json` when executed from Photoshop due to permissions issues. Another user has gotten this to work by running `chmod 777` on `card.json`, so this might work for you as well.

Let me know how you go with this!

**Comment by FlorisWarmenhoven** [comment]
From what I understand, and that's not much, the script is trying to copy the selection - but this selection doesn't exist. When I click 'OK' on the error popup in Photoshop and  press CMD + C it gives the same error.

The python script is correctly fetching the data and putting it in the card.json.

**Comment by ndepaola** [comment]
Ah alright - are you still getting the first error? Does it occur when you use `proxyTarget`, or only when you use `proxyAll`? The only time I've seen `proxyAll` break when `proxyTarget` works fine is when it's finding `.DS_Store` and trying to insert that as an image in the frame, which has been fixed.

When running properly, the script opens your art file, selects all, then copies that and closes the art file, and pastes it into the template. If it tries to open an empty file, there's nothing to select I guess and it can't copy anything.

**Comment by FlorisWarmenhoven** [comment]
So I figured I would clone your repo again, because you've made some new changes.
I've got one art file, named `Gilded Goose (Lindsey Look)` in the art folder.

I ran `proxyAll` and got this error: 
![image](https://user-images.githubusercontent.com/15650071/69005965-40946e80-0929-11ea-851c-fb06517ab328.png)

I then created a card.json and gave the entire folder chmod 777. Unfortunately this doesn't work, still. So I ran the Python script manually, using `python3 get_card_info.py "Gilded Goose"` which successfully generated the card.json file.

Now when I run proxyAll, I get this error:
![image](https://user-images.githubusercontent.com/15650071/69005955-235fa000-0929-11ea-8b6d-be03946d6414.png)

We're getting closer and closer...

**Comment by FlorisWarmenhoven** [comment]
Sorry, I forgot to copy over the templates. 
It opens, but gives me this:

![image](https://user-images.githubusercontent.com/15650071/69006043-2ad37900-092a-11ea-9a4c-82d27d7890ec.png)

**Comment by ndepaola** [comment]
Looks like the error is occurring when it tries to shift the rules text up in case it's overlapping with the text box. If you open the template and look in the *Text and Icons* group, can you see the layers *PT Top Reference* and *PT Adjustment Reference*? One reason it could be throwing an error is if they're not in place. If you don't have them, then the most recent version of the template should have them :) 

With regards to the art being cropped too large, you can try the fix I posted in the FAQ at the bottom of the main page - that's fixed it whenever I've seen this crop up.

I also noticed the expansion symbol gradient isn't quite right - could you also try the fix I posted in the FAQ for that and see if it works? 

Lastly, it seems like you might not have the MPLantin-Italics font installed, which is why the reminder text doesn't look quite right.

**Comment by FlorisWarmenhoven** [comment]
Alright, I've done the following:

- Downloaded the latest 'automated.zip' from your Google drive and replaced all the files in the template folder.
- Changed the art scaling from 100 to 50 as suggested by the FAQ (one note: FAQ said to open `frame.jsx` but you have since exported it to the functions file - you may want to change that)
- Changed the color thingy to divide by 2 instead of 4.

I ran `proxyAll.jsx` and I'm still greeted by this error:
![image](https://user-images.githubusercontent.com/15650071/69006758-27dd8600-0934-11ea-938f-eced53c706e8.png)

The art scales perfectly now, though. The italic text is perfect as well. 

At the moment, the script still fails to retrieve data from scryfall (or at least, can't write it to the .json file). It also doesn't automatically export the image, that probably has something to do with the previous error.

We're on the right track, I think we're close to having it work on Mac.

**Comment by ndepaola** [comment]
If the script is stopped by an error, it won't output an image yea. Right now I don't know why it'd be erroring, but you can comment out `verticallyFixText()` in `proxy.jsx` in the interim until we can fix it.

re: the font being slightly too large - the fonts available online are slightly different to the official fonts used by wizards in terms of kerning. It's rare that the card outputs will line up identically with real cards, but it tries to fit the text to the text box as best it can.

There should be a `debug.log` file in the `scripts` folder - if you open that, does it say something about a permission error? If it does, that's what's stopping the json from saving properly.

**Comment by FlorisWarmenhoven** [comment]
```
Asking Scryfall for information for: Gilded Goose
Found information for: Gilded Goose
{'name': 'Gilded Goose', 'rarity': 'rare', 'manaCost': '{G}', 'type': 'Creature — Bird', 'text': 'Flying\nWhen Gilded Goose enters the battlefield, create a Food token. (It\'s an artifact with "{2}, {T}, Sacrifice this artifact: You gain 3 life.")\n{1}{G}, {T}: Create a Food token.\n{T}, Sacrifice a Food: Add one mana of any color.', 'flavourText': '', 'power': '0', 'toughness': '2', 'layout': 'normal', 'colourIdentity': ['G']}
Traceback (most recent call last):
  File "/Users/floris/Desktop/cards/scripts/get_card_info.py", line 206, in <module>
    save_json(card_json)
  File "/Users/floris/Desktop/cards/scripts/get_card_info.py", line 151, in save_json
    with open("card.json", 'w') as f:
OSError: [Errno 30] Read-only file system: 'card.json'

```
Which is interesting, because I did already chmod'ed the card.json with 777.

Commenting out the verticallyFixText() worked - the card is now correctly exported. Here is the image:
<img width="1344" alt="Gilded Goose" src="https://user-images.githubusercontent.com/15650071/69007047-eb605900-0938-11ea-8048-e524cb6823a4.png">

The expansion symbol still seems off... Not sure why that is. Did I install the wrong font perhaps?

**Comment by FlorisWarmenhoven** [comment]
After some digging, I resolved the python script permission issue. I solved this by adding this line:
`new File(filePath + "/scripts/card.json").remove();` near the top of the proxy function. This allows python to create a new file every time, therefore sidestepping the permission issue.

I'm sure you could come up with a better solution - but this one seems to work.

Final question: where do you acquire your art? Say I'd like to get Wicked Wolf. I can't find any high res art, so I resort to downloading from scryfall (just the cropped image). Not really a fan of that.

**Comment by ndepaola** [comment]
- For Atraxa: Photoshop has an idiosyncrasy where if you have a text layer of font size 40, and scale it up by a factor of 2, it'll present itself as font size 80 in PS, but scripts will see it as being font size 40. What's happening here is the code that reduces the size of the card name layer in case it would overlap with the mana cost is setting the font size to what the code sees it as, meaning it's halving it. I thought I was thorough with remaking the text layers to avoid this, but I guess I missed the title in the box topper template, sorry. For this, I'd recommend making a new text layer with the same font and font size as the title in the box topper template, then naming it as the same thing, and deleting the old one. Let me know how that goes, then we can debug further from there if that doesn't fix it.

- For finishing off planeswalkers: what I tend to do is scale up the inserted scryfall scan to full size, then align the text of the card with that. From there, I do Save As and select png, and save & name it manually to the out folder. The default save settings for png's are fine for this. You can also resize the mask on the text box in case the middle strip of the planeswalker text box isn't positioned quite right. 

- For art, I typically use magic-ville.com. When you save images, they'll default to being html files - just rename them to use .jpg and you should be sweet. A little while back I developed a small Python utility to scrape card art crops from scryfall, throw them through waifu2x, then do some simple image processing to try to eliminate the rosette pattern. This is a bit of a last resort but the results are usually pretty respectable. I could have sworn I uploaded it to the repository, but I can't see it there - will reupload it tomorrow if you're interested. 

- I tried using your fix for `card.json`, and it still doesn't seem to want to work on my mac. Glad to hear it's working for you though! I'll keep digging around and see if I can get to the bottom of this.

**Comment by FlorisWarmenhoven** [comment]
Quick reply: try running this in the root work dir:
`sudo chmod a+rw .`

**Comment by ndepaola** [comment]
Doesn't seem to have worked for me, unfortunately

**Comment by ndepaola** [comment]
Hey hey - I updated the script + templates today to hopefully fix the expansion symbol gradient for other people's systems. Could you try pulling the latest changes & template and let me know if it renders properly or not? Thanks!

**Comment by FlorisWarmenhoven** [comment]
Alright, reporting back! I decided to clone your repo and start from scratch, because I couldn't remember how I fixed the Python script. I figured it out. I've listed all my steps below:

- Clone repo
- Download [automated.zip](http://automated.zip) and extract inside `workdir/templates`
- Create `workdir/art`, `workdir/out` and `workdir/out/border`
- Move two  art files, properly named, to `workdir/art`
- Run `proxyAll.jsx` - receive error:
![image](https://user-images.githubusercontent.com/15650071/69036570-79dee400-09e6-11ea-8cf8-519b0b8ded30.png)

- Most likely error due to Python script not running properly, check debug.log, see:
```
    Asking Scryfall for information for: Wicked Wolf
    Found information for: Wicked Wolf
    {'name': 'Wicked Wolf', 'rarity': 'rare', 'manaCost': '{2}{G}{G}', 'type': 'Creature — Wolf', 'text': "When Wicked Wolf enters the battlefield, it fights up to one target creature you don't control.\nSacrifice a Food: Put a +1/+1 counter on Wicked Wolf. It gains indestructible until end of turn. Tap it.", 'flavourText': '', 'power': '3', 'toughness': '3', 'layout': 'normal', 'colourIdentity': ['G']}
    Traceback (most recent call last):
      File "/Users/floris/Desktop/mtg-autoproxy/scripts/get_card_info.py", line 206, in <module>
        save_json(card_json)
      File "/Users/floris/Desktop/mtg-autoproxy/scripts/get_card_info.py", line 151, in save_json
        with open("card.json", 'w') as f:
    OSError: [Errno 30] Read-only file system: 'card.json'
```
- Run `sudo chmod a+rw .` in  workdir, try again. Same error.
- Run `sudo chmod -R 777 scripts/` in workdir, try again. Same error.
- Run `touch scripts/card.json`  in  workdir, try again. Same error.
- Change line 151 to `with open("/Users/floris/Desktop/cards/scripts/card.json", 'w') as f:` and delete card.json file. This fixes the problem! It works.
- Add `new File(filePath + "/scripts/card.json").remove();` to top of proxy file to delete the card every time. Then realised this isn't needed.
- Art is still messed up, so I'm reducing the percentage to 50 instead of 100. Line: `var percentageToScale = 50 * (Math.max(windowWidth / [imageWidth.as](http://imagewidth.as/)('px'), windowHeight / [imageHeight.as](http://imageheight.as/)('px')));`
- I am still getting this error:

![image](https://user-images.githubusercontent.com/15650071/69036596-86fbd300-09e6-11ea-8f8e-7aec8dec8fba.png)

- Commenting out `if (cardPower != null && cardTough != null) verticallyFixText(textLayerName);` on line 558 in `proxy.jsx`

Resulting card:
![image](https://user-images.githubusercontent.com/15650071/69036660-a7c42880-09e6-11ea-96d8-53bbfe801d0f.png)

**Comment by ndepaola** [comment]
Thank you so much for documenting this thoroughly! Seems like the crux of what stopped the python script from working was the filepath. I now have `with open(sys.path[0] + "/card.json", 'w') as f:` and this works properly on my Windows & macOS machines, so I'll push it to the repo in a bit. I'm hoping that messing around with `chmod` isn't necessary after this fix is included as well. 

I'm still not sure why `verticallyFixText` is breaking, but I'm sure I'll figure it out at some point. Good to see the expansion symbol is working for you now too!

**Comment by FlorisWarmenhoven** [comment]
I guess this issue turned into my bug reporting thread...

![image](https://user-images.githubusercontent.com/15650071/69878101-375db700-12c4-11ea-8869-13006e97ac6e.png)

The 'shadows' layer adds a weird looking white bit on the bottom left of Jace. Any idea why or how I can get rid of it?

Also the `verticallyFixText` still crashes the run. Not sure if it's a vital part.
The python script adjustments worked great by the way. One thing you forgot do do was add the changes you made on line 118 in the `get_card_info.py` to the line on 100. (Specifically the `sys.path[0]` part)

**Comment by ndepaola** [comment]
Hey - I see what you mean about the shadows layer. Not sure how I missed that, sorry! 

![image](https://user-images.githubusercontent.com/3079166/69879713-e07fce00-1313-11ea-8a13-a0e243a0649c.png)

I'm working on a box topper template for planeswalkers & adjusting the code to automate planeswalkers for that, so I might take this opportunity to improve my main planeswalker template a bit.

![image](https://user-images.githubusercontent.com/3079166/69879906-5b48e900-1314-11ea-9df9-78da67690511.png)

I'll take another look at verticallyFixText then. It's not critical most of the time, but it fixes instances of the rules text overlapping the PT box in some cases. Try proxying a Dragonlord Dromoka (or I think it's necessary on Hellrider as well) with that line commented out and you'll see what I mean.

Did you mean line 110 with saving the scryfall scan for planeswalkers?

**Comment by FlorisWarmenhoven** [comment]
Hell yes that planeswalker template looks awesome.

Yeah, where it saves the scan for scryfall.

**Comment by FlorisWarmenhoven** [comment]
Also - can you point me to a resource how you can have the head of the planeswalker 'above' the title bar? I know it's possible, I just don't know how. If you do know how - maybe you could do a little video tutorial on it?

**Comment by ndepaola** [comment]
absolutely! What you’ll first want to do is make a selection for the part you want to pop out of the frame. I find the magnetic lasso tool and pen tool are great for this. Then, the shortcut ctrl J will copy the selected part of the layer you’re on onto a new layer. Drag the new layer above the frame layers, and you should be good to go :)

**Comment by FlorisWarmenhoven** [comment]
I think it's safe to close this issue. Thank you for your help @ndepaola!
